const APPLICATION_DB_ERROR = 'APPLICATION_DB_ERROR'

const USER_END_DB_ERROR_INVALID = 'USER_END_DB_ERROR_INVALID'

const USER_END_DB_ERROR_CONFLICT = 'USER_END_DB_ERROR_CONFLICT'

module.exports = {
  APPLICATION_DB_ERROR,
  USER_END_DB_ERROR_INVALID,
  USER_END_DB_ERROR_CONFLICT
}
