const MODEL_CONSTRUCTION_ERROR = 'MODEL_CONSTRUCTION_ERROR'

const VALUE_ERROR = 'VALUE_ERROR'

const INVALID_RATIONAL_VALUE_ERROR = 'INVALID_RATIONAL_VALUE_ERROR'

const NOT_FOUND_ERROR = 'NOT_FOUND_ERROR'

module.exports = {
  MODEL_CONSTRUCTION_ERROR,
  VALUE_ERROR,
  INVALID_RATIONAL_VALUE_ERROR,
  NOT_FOUND_ERROR
}
