name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image - target test
        run: docker build . --file Dockerfile --tag chapost/clients-lab-measures-manager-be:test --target test
  
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Run image with tests suite
        run: docker run -it --rm test-node-docker-lab-clients:test

  # tests:

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x, 18.x]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm test
  
  deploy:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chapost/clients-lab-measures-manager-be:latest
      
    - name: Docker Push
      run: docker push chapost/clients-lab-measures-manager-be
