name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
  
  
  build:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      uses: docker/login-action@v2
      with:
          registry: chapost/clients-lab-measures-manager-be
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_USER }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chapost/clients-lab-measures-manager-be:latest
      
    - name: Docker Push
      run: docker push chapost/clients-lab-measures-manager-be
